### ISSUE TITLE
links don't work in public version, change eventually

### ISSUE THREAD

**Issue by JustinGOSSES** [nasa/concept-tagging-training#3]
2 links on the bottom of the page: https://github.com/nasa/concept-tagging-training/tree/master/src/dsconcept

Could either take off or replace with fuller docs on this version. 

Not immediate need

**Comment by bluetyson** [comment]
Justin, just trying one of the tests: Traceback (most recent call last):
  File "context.py", line 8, in <module>
    import app
  File "/home/ubuntu/concept-tagging-api/service/app.py", line 6, in <module>
    import dsconcept.get_metrics as gm
ModuleNotFoundError: No module named 'dsconcept'

setting up via local python - will grabbing those from the training repo work?
